name: Docker Build and Publish

on:
  push:
    branches:
      - main # Cambia questa sezione se il tuo branch principale ha un nome diverso

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t marcomontel/speedtest-cli .

    - name: Push Docker image
      run: docker push marcomontel/speedtest-cli

